language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t akashiice/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true akashiice/react-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-dev"
    bucket_name: "elasticbeanstalk-ap-south-1-944093395421"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY